"""empty message

Revision ID: 9a1b60a6d303
Revises: 
Create Date: 2026-06-04 15:28:52.779051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1b60a6d303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comptes', schema=None) as batch_op:
        batch_op.alter_column('numero_compte',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
        batch_op.alter_column('type_compte',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('derniere_connexion', sa.DateTime(), nullable=True))
        batch_op.alter_column('mot_de_passe',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.alter_column('mot_de_passe',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('derniere_connexion')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('statut')
        batch_op.drop_column('description')

    with op.batch_alter_table('comptes', schema=None) as batch_op:
        batch_op.alter_column('utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type_compte',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('numero_compte',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)

    # ### end Alembic commands ###
